-- Ensure ID autogenerates and primary key exists
DO $$
BEGIN
  -- Make id an identity column if it isn't already
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = 'contact_requests'
      AND c.column_name = 'id'
      AND c.is_identity = 'YES'
  ) THEN
    ALTER TABLE public.contact_requests
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  -- Ensure primary key on id
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.contact_requests'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE public.contact_requests
    ADD PRIMARY KEY (id);
  END IF;
END $$;

-- Enable Row Level Security (safe if already enabled)
ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts for public contact form (no read access)
DROP POLICY IF EXISTS "Allow anonymous inserts for contact form" ON public.contact_requests;
CREATE POLICY "Allow anonymous inserts for contact form"
ON public.contact_requests
FOR INSERT
TO anon
WITH CHECK (true);
